### ISSUE TITLE
Update to asciidoc 1.5.5-1

### ISSUE THREAD

**Issue by hypery2k** [anthonny/angular-asciidoc-directive#6]
Any plans to update to latest asciidoc?

**Comment by anthonny** [comment]
Hi @hypery2k 
Sure, i will update ASAP ;)

**Comment by hypery2k** [comment]
cool, thanks

**Comment by hypery2k** [comment]
thx, super fast. will you create a tag for bower.io?

**Comment by anthonny** [comment]
you are welcome, it should be good now, tag 0.2.0
